[application]

# App (Project) Name
name = "ultimate_tex"

# Dioxus App Default Platform
# desktop, web

default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "ultimate_tex"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.ultimate_tex"
publisher = "ultimate_tex"

icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico"
]

[bundle.macos]
files = {}
hardened_runtime = false
# adhoc signing
signing_identity = "-"